</div>
</div>
</body>
<!-- Footer -->
<footer class="font-small bg-dark text-white pt-2">
    <div>
        <div id="footer" class="col-xs-12">
            <div class="list-inline text-center py-2">
                <h5>The Auction House</h5>
            </div>
        </div>
    </div>
</footer>
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
</body>
</html>
</html>